name: Build and Export

permissions:
  contents: write

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: godot

jobs:
  build-rust-library:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: linux
            arch: x86_64
            name: libnt4_logging.so
          - target: aarch64-unknown-linux-gnu
            os: linux
            arch: arm64
            name: libnt4_logging.so
          - target: x86_64-pc-windows-gnu
            os: windows
            arch: x86_64
            name: nt4_logging.dll
          - target: aarch64-pc-windows-gnullvm
            os: windows
            arch: arm64
            name: nt4_logging.dll
          - target: aarch64-apple-darwin
            os: macos
            arch: arm64
            name: libnt4_logging.dylib

    steps:
      - uses: actions/checkout@v4

      - name: Cache Compiled Binary
        id: cache-binary
        uses: actions/cache@v3
        with:
          path: nt4_logging/target/${{ matrix.target }}/release/${{ matrix.name }}
          key: ${{ runner.os }}-binary-${{ matrix.target }}-${{ hashFiles('nt4_logging/src/**', 'nt4_logging/Cargo.toml', 'nt4_logging/Cargo.lock') }}

      - name: Install dependencies
        if: steps.cache-binary.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Install Rust
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Zig
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Install cargo-zigbuild
        if: steps.cache-binary.outputs.cache-hit != 'true'
        run: cargo install cargo-zigbuild

      - name: Cache Cargo registry
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache Cargo build
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: nt4_logging/target
          key: ${{ runner.os }}-cargo-build-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ matrix.target }}-

      - name: Setup MacOS SDK
        if: contains(matrix.target, 'apple') && steps.cache-binary.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/joseluisq/macosx-sdks/releases/download/12.3/MacOSX12.3.sdk.tar.xz
          tar -xf MacOSX12.3.sdk.tar.xz

      - name: Build
        if: steps.cache-binary.outputs.cache-hit != 'true'
        working-directory: nt4_logging
        run: |
          if [[ "${{ matrix.target }}" == *"apple"* ]]; then
            export SDK_PATH=$GITHUB_WORKSPACE/MacOSX12.3.sdk
            export SDKROOT=$SDK_PATH
            export RUSTFLAGS="-C link-arg=-isysroot -C link-arg=$SDK_PATH"
          fi
          cargo zigbuild --release --target ${{ matrix.target }}

      - name: Prepare Artifact
        run: |
          mkdir -p artifacts/${{ matrix.os }}/${{ matrix.arch }}
          cp nt4_logging/target/${{ matrix.target }}/release/${{ matrix.name }} artifacts/${{ matrix.os }}/${{ matrix.arch }}/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-lib-${{ matrix.os }}-${{ matrix.arch }}
          path: artifacts/${{ matrix.os }}/${{ matrix.arch }}/${{ matrix.name }}

  godot-export:
    needs: [build-rust-library]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Create bin directory
        run: mkdir -p godot/bin

      - name: Download Linux x64
        uses: actions/download-artifact@v4
        with:
          name: rust-lib-linux-x86_64
          path: godot/bin

      - name: Download Linux arm64
        uses: actions/download-artifact@v4
        with:
          name: rust-lib-linux-arm64
          path: godot/bin

      - name: Download Windows x64
        uses: actions/download-artifact@v4
        with:
          name: rust-lib-windows-x86_64
          path: godot/bin

      - name: Download Windows arm64
        uses: actions/download-artifact@v4
        with:
          name: rust-lib-windows-arm64
          path: godot/bin

      - name: Download MacOS arm64
        uses: actions/download-artifact@v4
        with:
          name: rust-lib-macos-arm64
          path: godot/bin

      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build Windows x86_64
        run: |
          mkdir -p build/windows_x86_64
          godot --headless --verbose --path godot --export-release "Windows x86_64" ../build/windows_x86_64/FRC_Visualization.exe
          zip -j build/FRC_Visualization_Windows_x86_64.zip build/windows_x86_64/FRC_Visualization.exe godot/bin/nt4_logging.dll

      - name: Build Windows arm64
        run: |
          mkdir -p build/windows_arm64
          godot --headless --verbose --path godot --export-release "Windows arm64" ../build/windows_arm64/FRC_Visualization.exe
          zip -j build/FRC_Visualization_Windows_arm64.zip build/windows_arm64/FRC_Visualization.exe godot/bin/nt4_logging.dll

      - name: Build Linux x86_64
        run: |
          mkdir -p build/linux_x86_64
          godot --headless --verbose --path godot --export-release "Linux x86_64" ../build/linux_x86_64/FRC_Visualization.x86_64
          zip -j build/FRC_Visualization_Linux_x86_64.zip build/linux_x86_64/FRC_Visualization.x86_64 godot/bin/libnt4_logging.so

      - name: Build Linux arm64
        run: |
          mkdir -p build/linux_arm64
          godot --headless --verbose --path godot --export-release "Linux arm64" ../build/linux_arm64/FRC_Visualization.arm64
          zip -j build/FRC_Visualization_Linux_arm64.zip build/linux_arm64/FRC_Visualization.arm64 godot/bin/libnt4_logging.so

      - name: Build macOS
        run: |
          mkdir -p build/macos
          godot --headless --verbose --path godot --export-release "macOS" ../build/macos/FRC_Visualization_MacOS.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            build/FRC_Visualization_Windows_x86_64.zip
            build/FRC_Visualization_Windows_arm64.zip
            build/FRC_Visualization_Linux_x86_64.zip
            build/FRC_Visualization_Linux_arm64.zip
            build/macos/FRC_Visualization_MacOS.zip